---
name: Check Python

permissions:
  pull-requests: read
  contents: read

on:
  push:
    paths:
      - "*.py"
  pull_request:
    paths:
      - "*.py"

jobs:
  python-test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ovirt/buildcontainer:el9stream

    steps:
      - name: prepare env
        run: |
          dnf install -y --setopt=tsflags=nodocs epel-release
          dnf install -y --setopt=tsflags=nodocs python3-flake8

      - name: Checkout sources
        uses: ovirt/checkout-action@main

      - name: Check Python files
        run: flake8-3 *.py
